language: node_js

node_js:
- "stable"

cache:
  directories:
  - "$HOME/.npm"

install:
- npm install

script:
- npm run build

deploy:
  email: "zach.toben@gmail.com"
  name: "Zach Toben"
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
